// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import EmailVerificationController from "./email_verification_controller"
application.register("email-verification", EmailVerificationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SubtitleMergedController from "./subtitle_merged_controller"
application.register("subtitle-merged", SubtitleMergedController)

import XiaohongshuDownloaderController from "./xiaohongshu_downloader_controller"
application.register("xiaohongshu-downloader", XiaohongshuDownloaderController)
